openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
tags:
  - name: /users
    description: 'all about users'
paths:
  /users:
    get:
      tags:
        - /users
      parameters:
        - name: login
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            json:
              schema: 
                $ref: '#components/schemas/userAnsver'
        '404':
          description: Not Found
          content:
            json:
              schema: 
                $ref: '#/components/schemas/errorMessage'
    post:
      tags:
        - /users
      description: ''
      requestBody:
        content:
          json:
            schema: 
              $ref: '#/components/schemas/payload'
      responses:
        '200':
          description: OK
          content:
            json:
              schema:
                $ref: '#/components/schemas/userAnsver'
        '400':
          description: Error
          content:
            json:
              schema: 
                $ref: '#/components/schemas/errorMessage'

  /users{id}:
    get:
      tags:
        - /users
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          schema: 
            type: integer
      responses:
        '200':
          description: OK
          content:
            json:
              schema: 
                $ref: '#components/schemas/userAnsver'
        '404':
          description: Not Found
          content:
            json:
              schema:
                $ref: '#components/schemas/errorMessage'
    patch:
      tags:
        - /users
      description: ''
      parameters: []
      responses:
        '200':
          description: OK
    delete:
      tags:
        - /users
      description: ''
      parameters: []
      responses:
        '200':
          description: OK
  /users/authenticate:
    post:
      tags:
        - /users
      description: ''
      parameters: []
      responses:
        '200':
          description: OK
components:
  schemas:
    userAnsver:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: [10]
        login:
          type: string
          example: [login]
        email:
          type: string
          example: [ii@mail.ru]
        password:
          type: string

    errorMessage:
      type: object
      properties:
          err:
            type: string

    payload:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
          
        